#include <osgDB/ObjectWrapper>

#include "resources/EResource.h"

REGISTER_OBJECT_WRAPPER(
	EResource,
	new ::EResource,
	::EResource,
	"osg::Object osg::Node ::EResource")
{
	ADD_STRING_SERIALIZER(ResourceName, "Untitled");
	ADD_STRING_SERIALIZER(Author, "");
	ADD_STRING_SERIALIZER(ResourcePath, "");
	ADD_STRING_SERIALIZER(ResourceDescription, "");

	ADD_BOOL_SERIALIZER(Global, true);

	BEGIN_ENUM_SERIALIZER(Copyright, UNSPECIFIED);
		ADD_ENUM_VALUE(COPYRIGHTED);
		ADD_ENUM_VALUE(FAIRUSE	  );
		ADD_ENUM_VALUE(HELD		  );
		ADD_ENUM_VALUE(PUBLIC	  );
		ADD_ENUM_VALUE(UNKNOWN	  );
		ADD_ENUM_VALUE(PERMISSION );
		ADD_ENUM_VALUE(WEB		  );
		ADD_ENUM_VALUE(UNSPECIFIED);
	END_ENUM_SERIALIZER();

	ADD_INT_SERIALIZER(MinYear, 0);
	ADD_INT_SERIALIZER(MaxYear, 0);
	ADD_BOOL_SERIALIZER(Reposition, 0);
	ADD_BOOL_SERIALIZER(AutoLaunch, 0);

	BEGIN_ENUM_SERIALIZER(ERType, ANNOTATION);
		ADD_ENUM_VALUE(URL);
		ADD_ENUM_VALUE(ANNOTATION);
		ADD_ENUM_VALUE(FILE);
	END_ENUM_SERIALIZER();

	ADD_FLOAT_SERIALIZER(LocalRange, .20);

	ADD_MATRIXD_SERIALIZER(CameraMatrix, osg::Matrixd());

	ADD_OBJECT_SERIALIZER(Category, ECategory, nullptr);
}
